import React, { ReactNode } from 'react';
import Head from 'next/head';
import Link from 'next/link';

interface Props {
  children: ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <div className="w-screen h-screen overflow-y-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-zinc-700/40">
        <header className="lg:w-screen max-w-screen-2xl mx-auto h-20 justify-between flex flex-row items-center text-sm lg:text-lg">
          <div className="flex flex-row gap-5 pl-10 lg:pl-20">
            <div className="lg:hidden sm:flex md:flex">
              <button>Burger</button>
            </div>
            <div className="lg:flex xl:flex 2xl:flex flex-row gap-5 md:hidden sm:hidden hidden">
              <Link href="/">Home</Link>
              <Link href="/docs">Docs</Link>
              <Link href="/service">Services</Link>
              <Link href="/maps">Maps</Link>
            </div>
          </div>
          <div className="flex flex-row gap-5 pr-10 lg:pr-20">
            <div className="lg:hidden sm:flex md:flex">
              <button>Burger</button>
            </div>
            <div className="lg:flex xl:flex 2xl:flex flex-row gap-5 md:hidden sm:hidden hidden">
              <Link href="/signup">Sign Up</Link>
              <Link href="/login">Login</Link>
            </div>
          </div>
        </header>
      </div>
      {children}
    </div>
  );
};

export default Layout;
