import React, { ReactNode } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import {
  Menu,
  MenuHandler,
  MenuList,
  MenuItem,
  Button,
  Typography,
} from '@material-tailwind/react';
import Footer from './Footer';
interface Props {
  children: ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-zinc-700/40">
        <header className="lg:w-screen max-w-screen-2xl mx-auto h-20 justify-between flex flex-row items-center text-sm lg:text-lg">
          <div className="flex flex-row gap-5 pl-10 lg:pl-20">
            <div className="lg:hidden sm:flex md:flex">
              <Menu placement="bottom-start">
                <MenuHandler>
                  <Button variant="text" color="blue-gray">
                    Open Menu
                  </Button>
                </MenuHandler>
                <MenuList className="border-none max-w-fit min-w-fit">
                  <MenuItem className="text-start">Menu Item 1</MenuItem>
                  <MenuItem className="text-start">Menu Item 2</MenuItem>
                  <MenuItem className="text-start">Menu Item 3</MenuItem>
                </MenuList>
              </Menu>
            </div>
            <div className="lg:flex xl:flex 2xl:flex flex-row gap-5 md:hidden sm:hidden hidden">
              <Link
                className="text-blue-gray-700 hover:text-green-500"
                href="/"
              >
                Home
              </Link>
              <Link
                className="text-blue-gray-700 hover:text-green-500"
                href="/docs"
              >
                Docs
              </Link>
              <Link
                className="text-blue-gray-700 hover:text-green-500"
                href="/service"
              >
                Services
              </Link>
              <Link
                className="text-blue-gray-700 hover:text-green-500"
                href="/maps"
              >
                Maps
              </Link>
            </div>
          </div>
          <div className="flex flex-row gap-5 pr-10 lg:pr-20">
            <div className="lg:hidden sm:flex md:flex">
              <Menu placement="bottom-end">
                <MenuHandler>
                  <Button variant="text" color="blue-gray">
                    Open Menu
                  </Button>
                </MenuHandler>
                <MenuList className="border-none max-w-fit min-w-fit">
                  <MenuItem className="text-end">Menu Item 1</MenuItem>
                  <MenuItem className="text-end">Menu Item 2</MenuItem>
                  <MenuItem className="text-end">Menu Item 3</MenuItem>
                </MenuList>
              </Menu>
            </div>
            <div className="lg:flex xl:flex 2xl:flex flex-row gap-5 md:hidden sm:hidden hidden">
              <Link
                className="text-blue-gray-700 hover:text-green-500"
                href="/signup"
              >
                Sign Up
              </Link>
              <Link
                className="text-blue-gray-700 hover:text-green-500"
                href="/login"
              >
                Login
              </Link>
            </div>
          </div>
        </header>
      </div>
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
